[tool.poetry]
name = "wn-lookup-gen"
version = "0.1.0"
description = "Raster processing utility"
authors = ["Gunjan <dgh007786007@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"


[tool.poetry.group.dev.dependencies]
sphinx = "^8.1.3"
sphinx-autodoc-typehints = "^2.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
